---
info:
  component: Api Gateway

server:
  port: ${PORT:${vcap.application.port:8765}}

---
spring:
  config:
    activate:
      on-profile: dev

endpoints:
  routes:
    enabled: true


---
spring:
  config:
    activate:
      on-profile: test


---
spring:
  config:
    activate:
      on-profile: cloud
