info:
  component: Discovery Service

server:
  port: ${PORT:${vcap.application.port:8761}}

eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 15
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME:user}:${EUREKA_PASSWORD:12345}@${EUREKA_URL}/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0
      enable-self-preservation: false
spring:
  security:
    enable-csrf: false
    user:
      name: ${EUREKA_USERNAME:user}
      password: ${EUREKA_PASSWORD:12345}

---
spring:
  config:
    activate:
      on-profile: test

---
spring:
  config:
    activate:
      on-profile: cloud
